### ISSUE TITLE
DataTable: Make `onFetchData` call refetchable

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/catalyst#121]
### Summary description of UI component feature
The DataTable should allow for a callback to make it possible to trigger a data refetch from the parent.

### Rationale for why this is necessary
The current Effect only allows for some fixed values that trigger a new fetch:
https://github.com/reactioncommerce/catalyst/blob/721fc0c761ad57d3bd59caca6ddbb7b68b411f4d/package/src/components/DataTable/helpers/useDataTable.js#L120

### Expected use cases
My usecase was Header sorting. Although this will probaly be directly integrated at some point, for now I could just pass a custom component as Header to display a sorted value and if it is ascending/descending and store that value on my parent component`s state.

I might be missing something obvious here as I'm just getting warm with hooks, but I found no way to instruct DataTable to reload the updated data.
Directly deriving these values in the onFetchData function on my parent component would not trigger an actual fetch on the DataTable.

Regarding that descrived usecase, apart from that specific one there might be other ones with external conditions that would need to make the table fetch updated data under some circumstances.

**Comment by mikemurray** [comment]
We certainly do plan to implement column sorting so you don't have to resort to hacking the hook to do so. We have nothing implemented at the moment so that's why `onFetchData` won't know if the column sorting just got updated.

`onFetchData` is not meant to be re-fetchable because it happens based on some need for react-table to want fresh data because of changes to filtering, sorting, pagination. If you want the force the data into the table, you pass it as a prop to the `useDataTable` hook, but then you're on the hook for state changes. 

https://github.com/reactioncommerce/catalyst/blob/721fc0c761ad57d3bd59caca6ddbb7b68b411f4d/package/src/components/DataTable/helpers/useDataTable.js#L12-L26

**Comment by janus-reith** [comment]
@mikemurray That is what i tried before, but passing data to `useDataTable`wouldn`t trigger a rerender.
The Effect Hook I linked before

https://github.com/reactioncommerce/catalyst/blob/721fc0c761ad57d3bd59caca6ddbb7b68b411f4d/package/src/components/DataTable/helpers/useDataTable.js#L120

would only run again if one of the defined fields changes:
globalFilter, onFetchData, setData, pageCount, setPageCount, tableState

None of them seemed suitable to pass in additional data, so for now I had to resort to forking `useDataTable` in order to pass additional fields.

**Comment by janus-reith** [comment]
Another use case: bulk actions.
How would I currently refetch after a mutation? As an alternative I tried for apollo to simply alter the cache of the query with returned mutation data, but that also wouldn't work without the exact original query including the query variables like the filters, which in turn are encapsulated in the callback.
